### ISSUE TITLE
how to setup with github page

### ISSUE THREAD

**Issue by rayway30419** [itisbenjamin/Nice_Blog#1]
Hi, 

I fork It to my [name].github.io repository but I visit my github page, it shows 404: There isn't a GitHub Pages site here.

Need something else for setting up this theme?

**Comment by itisbenjamin** [comment]
Hi there,

Can you show me all your settings in `_config.yml` file? 
That may help 😃 

Just incase, if you haven't change anything in your `_config.yml` file, you have to change some codes in it with your own informations to make things right.

**Comment by rayway30419** [comment]
Hi, @itisbenjamin 

I Just fork this repo and clone it then modify the content of tags of config.yml.

Github pages does not load the index.html.

Here is my configuration
```
# Site settings
title: RayWay's Blog
name: RayWay # your name
email: rayway30419@gmail.com # your email address
description: >
    My Blog # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rayway30419.github.io" # the base hostname & protocol for your site
twitter_username: rayway30419 # your Twitter username
github_username: rayway30419 # your Github username
disqus_username:  # your disqus username

google-analytics:  # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown

```

**Comment by itisbenjamin** [comment]
@rayway30419 
I just visited your repo, maybe you do changed your `_config.yml` file, but you haven't push it to Github, so you won't see anything.

Address to the `_config.yml` file in your Github repo:
https://github.com/rayway30419/rayway30419.github.io/blob/master/_config.yml

You should change it, and then push the modified files into your repo on Github.

Then everything can work 😃

**Comment by rayway30419** [comment]
@itisbenjamin 

Now it works well, Thanks! 👍
