### ISSUE TITLE
Wrong path for feed.xml

### ISSUE THREAD

**Issue by ziglef** [itisbenjamin/Nice_Blog#2]
Hey, i started to test out your theme for my personal blog and i must say I'm very pleased with the looks of it.

That said, while setting it up i noticed that the path to the feed.xml file was wrongly configured on [about.html](https://github.com/itisbenjamin/Nice_Blog/blob/master/about.html)

It's currently `<a href="{{ site.url}}/feed.xml"> Rss</a>` and i think that it should be `<a href="{{ site.baseurl}}/feed.xml"> Rss</a>`

Atleast using github pages the previous gives a not found error while the second option works.

**EDIT:** Formatting

**Comment by itisbenjamin** [comment]
Hi @ziglef 
Thanks for your issue!

I changed it to `<a href="{{ site.url }}{{ site.baseurl }}/feed.xml"> Rss</a>`
Everything should be fine now :smile 

PS: Just guessing, cause I cannot find your repo...Have you changed your `_config.yml` file? If you haven't change [this line](https://github.com/itisbenjamin/Nice_Blog/blob/master/_config.yml#L8), I think maybe this is the reason caused this mistake.

**Comment by ziglef** [comment]
Hey, you can check the repo @ https://github.com/ziglef/blog

I had in fact changed the line so that shouldn't be the problem.

Also i have also changed in [post.html](https://github.com/itisbenjamin/Nice_Blog/blob/master/_layouts/post.html) the line ` <a class="post-tags-item" href="/tags/">{{ tag }}</a>` to `<a class="post-tags-item" href="{{ site.baseurl }}/tags/">{{ tag }}</a>` and in [tags.html](https://github.com/itisbenjamin/Nice_Blog/blob/master/tags.html) i changed `<p><a href="{{ post.url }}">` to `<p><a href="{{ post.url | prepend: site.baseurl }}">`

With those changes i think everything is running fine on github-pages.

I haven't got the chance to try it with a account domain like https://user.github.io but with a pages domain like https://user.github.io/blog everything is working fine.

Hope this helps and thanks for the great template :)

**Comment by itisbenjamin** [comment]
@ziglef

Wonderful work!
Ive fixed them all, many thanks! 😄

**Comment by ziglef** [comment]
Just glad i could help. Continue with the great work!
